app:
  jwt:
    secret: e21fff8c5d8cfdb9da9e20f3df89300126a9f9e936c2f29451ff592672cc7afa
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 2592000000
spring:
  datasource:
    url: jdbc:sqlite:swapi.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  sql:
    init:
      mode: always

logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.springframework.security: DEBUG